# IMPORTING LIBRARIES

In [1]:
# IMPORTING NUMPY
import numpy as np
# IMPORTING PANDAS
import pandas as pd
# IMPORTING TENSORFLOW
import tensorflow as tf
# IMPORTING MATPLOTLIB
import matplotlib.pyplot as plt
# IMPORTING JSON
import json

# LOAD JSON FILE

In [2]:
# OPEN JSON FILE
JSON_DATA=open('Intent.json','r')
# CONVERT DATA INTO DICTIONARY FORMAT
data=json.load(JSON_DATA)
# GET INTENT DATA FROM THE DICTIONARY
intents_list= data['intents']
# EMPTY LIST FOR TAG
tags=[]
# EMPTY LIST FOR INPUT 
inputs=[]
for data in intents_list:
  patterns=data['text']
  for p in patterns:
    tags.append(data['intent'])
    inputs.append(p)


In [3]:
# TAGS
tags

['Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'goodbye',
 'goodbye',
 'goodbye',
 'goodbye',
 'goodbye',
 'goodbye',
 'goodbye',
 'goodbye',
 'goodbye',
 'goodbye',
 'thanks',
 'thanks',
 'thanks',
 'thanks',
 'thanks',
 'thanks',
 'thanks',
 'thanks',
 'thanks',
 'thanks',
 'tasks',
 'tasks',
 'tasks',
 'tasks',
 'tasks',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQu

In [4]:
# INPUTS
inputs

['Hi',
 'Hi there',
 'Hola',
 'Hello',
 'Hello there',
 'Hya',
 'Hya there',
 'Bye',
 'See you later.',
 'Goodbye',
 'Have a great day.',
 'See you next time.',
 'It was my pleassure.',
 'Take care.',
 'See ya!',
 'Catch you later.',
 'Ciao.',
 'Thanks',
 'Thank you',
 "That's helpful",
 "Thank's a lot!",
 'Tnx',
 'Wow',
 'Great!',
 'Good!',
 'That nice!',
 'Amazing!',
 'What can you do?',
 'What are your features?',
 'What are you abilities.',
 'Can you sing.',
 'Can you talk.',
 'My user is Adam',
 'This is Adam',
 'I am Adam',
 'It is Adam',
 'My user is Bella',
 'This is Bella',
 'I am Bella',
 'It is Bella',
 'How are you?',
 'Hi how are you?',
 'Hello how are you?',
 'Hola how are you?',
 'How are you doing?',
 'Hope you are doing well?',
 'Hello hope you are doing well?',
 'Good thanks! My user is Adam',
 'Good thanks! This is Adam',
 'Good thanks! I am Adam',
 'Good thanks! It is Adam',
 'Great thanks! My user is Bella',
 'Great thanks! This is Bella',
 'Great thanks! I am Bell

In [5]:
# CONVERT DATA INTO DATAFRAME
dataset=pd.DataFrame(
    {
        'inputs':inputs,
     'tags':tags
    }
)
# VIEW DATASET
dataset

inputs       tags
0                                           Hi   Greeting
1                                     Hi there   Greeting
2                                         Hola   Greeting
3                                        Hello   Greeting
4                                  Hello there   Greeting
..                                         ...        ...
190    Can you prove you are self aware please  SelfAware
191  Can you prove you have a conscious please  SelfAware
192                 prove you have a conscious  SelfAware
193                           Tell me a story?    stories
194                   Can you tell me a story.    stories

[195 rows x 2 columns]

# TEXT PROCESSING

In [6]:
import re
corpus=[]
for indx in range(0,len(dataset['inputs'])):
    temp=re.sub('[^A-Za-z]',' ',dataset['inputs'][indx])
    temp=re.sub(' +',' ',temp)
    corpus.append(temp)

In [7]:
corpus

['Hi',
 'Hi there',
 'Hola',
 'Hello',
 'Hello there',
 'Hya',
 'Hya there',
 'Bye',
 'See you later ',
 'Goodbye',
 'Have a great day ',
 'See you next time ',
 'It was my pleassure ',
 'Take care ',
 'See ya ',
 'Catch you later ',
 'Ciao ',
 'Thanks',
 'Thank you',
 'That s helpful',
 'Thank s a lot ',
 'Tnx',
 'Wow',
 'Great ',
 'Good ',
 'That nice ',
 'Amazing ',
 'What can you do ',
 'What are your features ',
 'What are you abilities ',
 'Can you sing ',
 'Can you talk ',
 'My user is Adam',
 'This is Adam',
 'I am Adam',
 'It is Adam',
 'My user is Bella',
 'This is Bella',
 'I am Bella',
 'It is Bella',
 'How are you ',
 'Hi how are you ',
 'Hello how are you ',
 'Hola how are you ',
 'How are you doing ',
 'Hope you are doing well ',
 'Hello hope you are doing well ',
 'Good thanks My user is Adam',
 'Good thanks This is Adam',
 'Good thanks I am Adam',
 'Good thanks It is Adam',
 'Great thanks My user is Bella',
 'Great thanks This is Bella',
 'Great thanks I am Bella',
 'G

In [8]:
tokenizer=tf.keras.preprocessing.text.Tokenizer(num_words=2000)
tokenizer.fit_on_texts(corpus)
X=tokenizer.texts_to_sequences(corpus)
X=tf.keras.preprocessing.sequence.pad_sequences(X)
Y=dataset.iloc[:,-1].values

In [9]:
print(X)

[[ 0  0  0 ...  0  0 59]
 [ 0  0  0 ...  0 59 60]
 [ 0  0  0 ...  0  0 77]
 ...
 [ 0  0  0 ... 48 11 76]
 [ 0  0  0 ...  2 11 94]
 [ 0  0  0 ...  2 11 94]]


In [10]:
len(X[0])

9

In [11]:
print(Y)

['Greeting' 'Greeting' 'Greeting' 'Greeting' 'Greeting' 'Greeting'
 'Greeting' 'goodbye' 'goodbye' 'goodbye' 'goodbye' 'goodbye' 'goodbye'
 'goodbye' 'goodbye' 'goodbye' 'goodbye' 'thanks' 'thanks' 'thanks'
 'thanks' 'thanks' 'thanks' 'thanks' 'thanks' 'thanks' 'thanks' 'tasks'
 'tasks' 'tasks' 'tasks' 'tasks' 'GreetingResponse' 'GreetingResponse'
 'GreetingResponse' 'GreetingResponse' 'GreetingResponse'
 'GreetingResponse' 'GreetingResponse' 'GreetingResponse'
 'CourtesyGreeting' 'CourtesyGreeting' 'CourtesyGreeting'
 'CourtesyGreeting' 'CourtesyGreeting' 'CourtesyGreeting'
 'CourtesyGreeting' 'CourtesyGreetingResponse' 'CourtesyGreetingResponse'
 'CourtesyGreetingResponse' 'CourtesyGreetingResponse'
 'CourtesyGreetingResponse' 'CourtesyGreetingResponse'
 'CourtesyGreetingResponse' 'CourtesyGreetingResponse' 'CurrentHumanQuery'
 'CurrentHumanQuery' 'CurrentHumanQuery' 'CurrentHumanQuery'
 'CurrentHumanQuery' 'CurrentHumanQuery' 'CurrentHumanQuery' 'alive'
 'alive' 'alive' 'help' 'help

In [12]:
from sklearn.preprocessing import LabelEncoder
encodeY=LabelEncoder()
Y_encoded=encodeY.fit_transform(Y)
Y_encoded

array([ 7,  7,  7,  7,  7,  7,  7, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 29, 29, 29, 29, 29,  8,  8,
        8,  8,  8,  8,  8,  8,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,
        3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4, 23, 23, 23, 26, 26, 26,
       26, 26, 26, 26, 26, 26, 26, 24, 24, 24, 24, 22, 22, 22, 22, 27, 27,
       27, 27, 10, 10, 10, 10, 10, 10, 14, 14, 14, 14, 14, 14, 14, 19, 19,
       19, 19, 19, 19, 19, 18, 18, 18, 18, 18, 18, 11, 11, 11, 11, 11, 11,
       11, 20, 20, 20, 20, 20, 20, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17,
       17,  5,  5,  5,  5,  1,  1,  1,  1,  1,  1, 21, 21, 21, 21, 21, 21,
        0,  0,  0,  0,  0,  0,  0,  6,  6,  6,  6,  6,  6,  9,  9,  9,  9,
        9,  9, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 15,
       15, 15, 15, 15, 15, 15, 28, 28])

In [13]:

Y=Y.reshape(len(Y),1)
print(Y)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
CT=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
Y=CT.fit_transform(Y).toarray()


[['Greeting']
 ['Greeting']
 ['Greeting']
 ['Greeting']
 ['Greeting']
 ['Greeting']
 ['Greeting']
 ['goodbye']
 ['goodbye']
 ['goodbye']
 ['goodbye']
 ['goodbye']
 ['goodbye']
 ['goodbye']
 ['goodbye']
 ['goodbye']
 ['goodbye']
 ['thanks']
 ['thanks']
 ['thanks']
 ['thanks']
 ['thanks']
 ['thanks']
 ['thanks']
 ['thanks']
 ['thanks']
 ['thanks']
 ['tasks']
 ['tasks']
 ['tasks']
 ['tasks']
 ['tasks']
 ['GreetingResponse']
 ['GreetingResponse']
 ['GreetingResponse']
 ['GreetingResponse']
 ['GreetingResponse']
 ['GreetingResponse']
 ['GreetingResponse']
 ['GreetingResponse']
 ['CourtesyGreeting']
 ['CourtesyGreeting']
 ['CourtesyGreeting']
 ['CourtesyGreeting']
 ['CourtesyGreeting']
 ['CourtesyGreeting']
 ['CourtesyGreeting']
 ['CourtesyGreetingResponse']
 ['CourtesyGreetingResponse']
 ['CourtesyGreetingResponse']
 ['CourtesyGreetingResponse']
 ['CourtesyGreetingResponse']
 ['CourtesyGreetingResponse']
 ['CourtesyGreetingResponse']
 ['CourtesyGreetingResponse']
 ['CurrentHumanQuery']
 ['C

In [14]:
print(Y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [15]:
Y.shape

(195, 31)

In [16]:
tokenizer.word_index

{'you': 1,
 'me': 2,
 'i': 3,
 'is': 4,
 'are': 5,
 'what': 6,
 'can': 7,
 'do': 8,
 'thanks': 9,
 'the': 10,
 'a': 11,
 'your': 12,
 'am': 13,
 'tell': 14,
 'please': 15,
 'name': 16,
 'who': 17,
 'help': 18,
 'pod': 19,
 'bay': 20,
 'door': 21,
 'see': 22,
 'time': 23,
 'adam': 24,
 'bella': 25,
 'to': 26,
 'open': 27,
 'it': 28,
 'my': 29,
 'real': 30,
 'not': 31,
 'prove': 32,
 'great': 33,
 'thank': 34,
 'good': 35,
 'how': 36,
 'talking': 37,
 'know': 38,
 'gossip': 39,
 'why': 40,
 'bye': 41,
 'goodbye': 42,
 's': 43,
 'call': 44,
 'need': 45,
 'will': 46,
 'hello': 47,
 'have': 48,
 'user': 49,
 'this': 50,
 'for': 51,
 'mr': 52,
 'dutta': 53,
 'wasn': 54,
 't': 55,
 'very': 56,
 'self': 57,
 'aware': 58,
 'hi': 59,
 'there': 60,
 'later': 61,
 'that': 62,
 'doing': 63,
 'hope': 64,
 'well': 65,
 'in': 66,
 'with': 67,
 'about': 68,
 'ok': 69,
 'quiet': 70,
 'clever': 71,
 'girl': 72,
 'any': 73,
 'some': 74,
 'joke': 75,
 'conscious': 76,
 'hola': 77,
 'hya': 78,
 'was': 79,
 

In [17]:
MODEL=tf.keras.models.Sequential()
MODEL.add(tf.keras.layers.Dense(units=30,activation='relu'))
MODEL.add(tf.keras.layers.Dense(units=60,activation='relu'))
MODEL.add(tf.keras.layers.Dense(units=90,activation='relu'))
MODEL.add(tf.keras.layers.Dense(units=100,activation='relu'))
MODEL.add(tf.keras.layers.Dense(units=150,activation='relu'))
MODEL.add(tf.keras.layers.Dense(units=31,activation='softmax'))
MODEL.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
MODEL.fit(X,Y,batch_size=10,epochs=400)

Epoch 1/400
20/20 [==============================] - 1s 3ms/step - loss: 4.5796 - accuracy: 0.0205
Epoch 2/400
20/20 [==============================] - 0s 3ms/step - loss: 3.1236 - accuracy: 0.1487
Epoch 3/400
20/20 [==============================] - 0s 3ms/step - loss: 2.7669 - accuracy: 0.2308
Epoch 4/400
20/20 [==============================] - 0s 3ms/step - loss: 2.5122 - accuracy: 0.2923
Epoch 5/400
20/20 [==============================] - 0s 4ms/step - loss: 2.3204 - accuracy: 0.3385
Epoch 6/400
20/20 [==============================] - 0s 3ms/step - loss: 2.1367 - accuracy: 0.4000
Epoch 7/400
20/20 [==============================] - 0s 3ms/step - loss: 2.0274 - accuracy: 0.3897
Epoch 8/400
20/20 [==============================] - 0s 4ms/step - loss: 1.9302 - accuracy: 0.4154
Epoch 9/400
20/20 [==============================] - 0s 3ms/step - loss: 1.8274 - accuracy: 0.4667
Epoch 10/400
20/20 [==============================] - 0s 3ms/step - loss: 1.7482 - accuracy: 0.4615
Epoch 11/

In [18]:
input_text=np.array(tokenizer.texts_to_sequences(['Hi there']))
padding_size=9-len(input_text[0])
input_text=np.pad(input_text[0],(padding_size,0),'constant',constant_values=(0,))
input_text=[list(input_text)]
input_text=np.array(input_text)
input_text

array([[ 0,  0,  0,  0,  0,  0,  0, 59, 60]])

In [19]:
P=MODEL.predict(input_text)

1/1 [==============================] - 0s 243ms/step


In [20]:
predict_index=np.argmax(P)

In [21]:
print(encodeY.inverse_transform([predict_index]))

['Greeting']


In [22]:
import random


def CHATBOT(input):
    input_text = np.array(tokenizer.texts_to_sequences([input]))
    padding_size = 9-len(input_text[0])
    input_text = np.pad(input_text[0], (padding_size, 0),
                    'constant', constant_values=(0,))
    input_text = [list(input_text)]
    input_text = np.array(input_text)
    
    P=MODEL.predict(input_text)
    intent=encodeY.inverse_transform([np.argmax(P)])
    for data in intents_list:
        if data['intent']==intent:
            res=data['responses']
            break
    res_indx=random.randint(0,len(res)-1)
    print("CHATBOT : "+res[res_indx])

In [23]:
while(True):
    user_input=input("IN :")
    if user_input=='0':
        break
    else:
        CHATBOT(user_input)

IN : hi


1/1 [==============================] - 0s 31ms/step
CHATBOT : Hi there, how can I help?


IN : joke


1/1 [==============================] - 0s 31ms/step
CHATBOT : Hello, thanks for visiting.


IN : what are you doing


1/1 [==============================] - 0s 31ms/step
CHATBOT : I can talk and do things for you


IN : help


1/1 [==============================] - 0s 31ms/step
CHATBOT : One moment


IN : help


1/1 [==============================] - 0s 31ms/step
CHATBOT : One moment


IN : stories


1/1 [==============================] - 0s 141ms/step
CHATBOT : Any time!


IN : tell me story


1/1 [==============================] - 0s 31ms/step
CHATBOT : Right now i'm in developing stage as soon i'm developed, I can do everything


IN : who created you?


1/1 [==============================] - 0s 47ms/step
CHATBOT : Mr. Dutta is my creator.


IN : 0


In [24]:
MODEL.save('model.h5')

In [27]:
import pickle
pickle.dump(encodeY,open('encodeY.pkl','wb'))

In [28]:
pickle.dump(tokenizer,open('tokenizer.pkl','wb'))